site_name: UFSIT CCDC Guidebook

repo_name: decaby7e/ccdc-tutorial
repo_url: https://github.com/decaby7e/ccdc-tutorial
edit_uri: "https://github.com/decaby7e/ccdc-tutorial/edit/master/docs"

nav:
  - Getting Started: index.md
  - Competition Info:
    - Important Dates: meta/itenerary.md
    - Resources: meta/resources.md
  - Guidebook:
    - 1. Fundamentals: guide/fundamentals.md
    - 2. Services: guide/services.md
    - 3. Networking: guide/networking.md
    - 4. Business Affairs: guide/business.md
    - 5. Strategy: guide/strategy.md

theme:
  name: material
  logo: assets/images/sit.png
  favicon: assets/images/sit.png
  features:
    - navigation.tabs

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - mdx_truly_sane_lists
